name: Production Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
            
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.7
      - name: "Build Site"
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy static site to S3 bucket
        run: aws s3 sync _site/ s3://${{ secrets.AWS_PRODUCTION_BUCKET_NAME}} --delete --exclude ".git/*" --exclude ".gitignore" --exclude ".github/*"
